describe('empty spec', () => {
  it('passes', () => {
    //cy.visit('http://localhost:3000/questions/new')
    cy.visit('http://localhost:3000/')
    cy.contains('Log in with your Wizeline account').click()
    cy.get('#username').type('pato.santos10@gmail.com')
    cy.get('#password').type('A01197723$')
    cy.contains('Continue').click()
    cy.reload()
    cy.get('#btnAccept').click()
    cy.get('#ask-button').click()
    cy.get('.sc-gYMRRK').click()
    cy.get('.sc-DdwlG').type('What should I do if I test positive?')
    cy.get('.sc-dwVMhp').click()
  })
})